--CONSTRAINTS

CREATE TABLE DPT --(PARENT TABLE)
(
	DPT_ID INT PRIMARY KEY,
	DPT_NAME VARCHAR(50)
)

DROP TABLE DPT

INSERT INTO DPT VALUES (1,'HR'),(2,'TRAINEE'),(3,'SALES'),(4,'MANAGER') 

CREATE TABLE EMP1 --(CHILD TABLE)
(
	EMP_ID INT PRIMARY KEY,
	EMP_NAME VARCHAR(50),
	DPT_ID INT DEFAULT 1 FOREIGN KEY REFERENCES DPT(DPT_ID)
)

DROP TABLE EMP1

INSERT INTO EMP1 VALUES (111,'HARSH',1), (112,'DEEP',2), (113,'ARSH',3), (114,'HEMA',4)
INSERT INTO EMP1(EMP_ID,EMP_NAME) VALUES (115,'HEMA') --(FOREIGN KEY WILL ACCEPT THE NULL VALUE)

INSERT INTO EMP1 VALUES (116,'PRIYA',5)

INSERT INTO EMP1 VALUES (117,'HARSH',8) --(NOT ACCEPTED BCS THERE IS NO EMP_ID 8 IN PARENT TABLE)

DELETE FROM DPT WHERE DPT_ID =3

SELECT * FROM DPT
SELECT * FROM EMP1


--TO DELETE OR UPDATE THE PARENT TABLE

--REFERENCIAL INTEGRITY

--1. ON DELETE CASCADE, ON UPDATE CASCADE

ALTER TABLE EMP1 DROP CONSTRAINT FK__EMP1__DPT_ID__1DB06A4F

ALTER TABLE EMP1 
ADD CONSTRAINT FK_EMP_DPR_ID 
FOREIGN KEY (DPT_ID) 
REFERENCES DPT(DPT_ID)
ON DELETE CASCADE ON UPDATE CASCADE

DELETE FROM DPT WHERE DPT_NAME='MANAGER'
UPDATE DPT SET DPT_NAME='FINANCIAL' WHERE DPT_ID=3

SELECT * FROM DPT
SELECT * FROM EMP1


--2. ON DELETE SET NULL, ON UPDATE SET NULL

ALTER TABLE EMP1 DROP CONSTRAINT FK_EMP_DPR_ID

ALTER TABLE EMP1 
ADD CONSTRAINT FK_EMP_DPR_ID 
FOREIGN KEY (DPT_ID) 
REFERENCES DPT(DPT_ID)
ON DELETE SET NULL ON UPDATE SET NULL

DELETE FROM DPT WHERE DPT_NAME='MANAGER'
UPDATE DPT SET DPT_NAME='FINANCIAL' WHERE DPT_ID=3

SELECT * FROM DPT
SELECT * FROM EMP1


--3. ON DELETE SET DEFAULT ON DELETE SET DEFAULT

CREATE TABLE DPT --(PARENT TABLE)
(
	DPT_ID INT PRIMARY KEY,
	DPT_NAME VARCHAR(50)
)

DROP TABLE DPT

INSERT INTO DPT VALUES (1,'HR'),(2,'TRAINEE'),(3,'SALES'),(4,'MANAGER') 

CREATE TABLE EMP1 --(CHILD TABLE)
(
	EMP_ID INT PRIMARY KEY,
	EMP_NAME VARCHAR(50),
	DPT_ID INT DEFAULT 1 FOREIGN KEY REFERENCES DPT(DPT_ID) ON DELETE SET DEFAULT ON UPDATE SET DEFAULT 
)

DROP TABLE EMP1

INSERT INTO EMP1 VALUES (111,'HARSH',1), (112,'DEEP',2), (113,'ARSH',3), (114,'HEMA',4)
INSERT INTO EMP1(EMP_ID,EMP_NAME) VALUES (115,'HEMA') --(FOREIGN KEY WILL ACCEPT THE NULL VALUE)

INSERT INTO EMP1 VALUES (116,'PRIYA',5)

INSERT INTO EMP1 VALUES (117,'HARSH',8) --(NOT ACCEPTED BCS THERE IS NO EMP_ID 8 IN PARENT TABLE)

DELETE FROM DPT WHERE DPT_ID =3

SELECT * FROM DPT
SELECT * FROM EMP1

--CHANGES FOR 3rd one

ALTER TABLE EMP1 DROP CONSTRAINT FK_EMP_DPR_ID

DELETE FROM DPT WHERE DPT_NAME='MANAGER'
UPDATE DPT SET DPT_NAME='FINANCIAL' WHERE DPT_ID=3
DELETE FROM DPT WHERE DPT_NAME='TRAINEE'

SELECT * FROM DPT
SELECT * FROM EMP1


