CREATE TABLE EMP
(
	ID INT,
	NAME VARCHAR (50),
	DEPARTMENT VARCHAR(50),
	SALARY INT
)

INSERT INTO EMP VALUES (1,'GEETHA','HR',45000)
INSERT INTO EMP VALUES (2,'PRIYA','MANAGER',55000)
INSERT INTO EMP VALUES (3,'PAVITRA','SALES',75000)
INSERT INTO EMP VALUES (4,'NITHYA','ANALYST',65000)
INSERT INTO EMP VALUES (5,'DEEPA','TRAINEE',85000)
INSERT INTO EMP VALUES (6,'HEMA','FINANCIAL',95000)

SELECT * FROM EMP
